config/routes.rb
Rails.application.routes.draw do
    
  resources :tickets
  root  'static_pages#home'
  match '/reservation',  to: 'tickets#new',            via: 'get'
  match '/search',  to: 'tickets#search',            via: 'get'
  match '/show',  to: 'tickets#show',            via: 'get'
  

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	validates :from, presence: true, length: { maximum: 50 }
	validates :to, presence: true, length: { maximum: 50 }
	VALID_DATE_REGEX = /\A(\d\d)[\/-](\d\d)[\/-](\d\d\d\d)\z/
	validates :date_of_journey, presence: true, format: { with: VALID_DATE_REGEX }
	validates :journey_direction, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	def new
		@ticket = Ticket.new
	end

	def show
		@ticket = Ticket.find(params[:id])
	end

	def create
		@ticket = Ticket.new(ticket_params)    
    		if @ticket.save
    			thread = Thread.new { sleep 60 }
			session[:thread] = thread.object_id
     			redirect_to search_path
    		else
      			render 'new'
    		end
	end

	def search
		if ObjectSpace._id2ref(session[:thread].to_i).alive?
			render 'search'
		else
			render 'show'
		end	
	end

	private

	def ticket_params
      		params.require(:ticket).permit(:from, :to, :date_of_journey, :journey_direction)
    	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Book My Trip"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created By
    <a href="https://github.com/kunal-das">Kunal Das</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", 'https://www.facebook.com/kunal.das.351' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%#= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%#= link_to "Help",    '#' %></li>
          <li><%#= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @ticket.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@ticket.errors.count, "error") %>.
    </div>
    <ul>
    <% @ticket.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Welcome to Book My Trip</h1>

  <p><h2>This is the place where you can plan your dream vacations and trips.</h2></p>

  <%= link_to "Book  It Now!", reservation_path, class: "btn btn-large btn-primary" %>
</div>

<%#= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/tickets/new.html.erb
<% provide(:title, 'Tickets Reservation Details') %>

<h1>Tickets Reservation Details</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@ticket) do |tick| %>
      <%= render 'shared/error_messages' %>

      <%= tick.label :from %>
      <%= tick.text_field :from %>

      <%= tick.label :to %>
      <%= tick.text_field :to %>

      <%= tick.label :date_of_journey %>
      <%= tick.text_field :date_of_journey %>

      <%= tick.radio_button(:journey_direction, "One-Way", :checked => true) %>
      <%= tick.label(:journey_direction, "One-Way") %>
	  <%= tick.radio_button(:journey_direction, "Two-Way") %>
	  <%= tick.label(:journey_direction, "Two-Way") %>
	  

      <%#= tick.label :password_confirmation, "Confirmation" %>
      <%#= tick.password_field :password_confirmation %>

      <%= tick.submit "Search", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tickets/search.html.erb
<% provide(:title, 'Search') %>
<h3>Pack Your Bags While We Are Searching</h3>
<meta http-equiv="refresh" content="1; url=/search">

app/views/tickets/show.html.erb
<% provide(:title, 'Search Results') %>
<h1>Search Results</h1>
<h2>Hey we found some tickets for you.</h2>